gentoo-audio/audio-overlay

media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild

@mrVanDalo this is the ebuild as I have it locally with some cleanups and additions (like adding a proper `.desktop` file, adding an icon, etc).
This one works for me doing some basic composition in it.
I do see some error message in the console when running it though, though it seems to be mainly a carla issue
```
❯ bitwig-studio 
JRE Path: //opt/bitwig-studio/lib/jre
Could not read directory contents: /usr/lib/carla/carla-bridge-native
Could not read directory contents: /usr/lib/carla/carla-bridge-lv2-gtk3
Could not read directory contents: /usr/lib/carla/libcarla_utils.so
Could not read directory contents: /usr/lib/carla/carla-bridge-lv2-modgui
Could not read directory contents: /usr/lib/carla/carla-bridge-lv2-qt5
Could not read directory contents: /usr/lib/carla/carla-bridge-lv2-x11 …
```

Update bitwig:1 ebuild

---

media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild

Whilst on GNOME the correct icon was shown in the application launcher it wasn't shown in the window manager (i.e. when alt-tabbing, or when viewing the "expose").
For reasons unknown to me this was caused by the `.desktop` file not having the same name as the executable. Since eutils's `dodesktop` effectively generates a `<executable>-<package name>.desktop` file, ie `bitwig-studio-bitwig-studio.desktop` this combo didn't work.
Fixed by replacing the `dodesktop` call with copying bitwig's own `.desktop` file.
Needed two `sed` statements to make it compliant with the freedesktop spec. I'll send a support mail to bitwig to request them to fix these two items upstream.

media-sound/bitwig-studio fix window manager icon on GNOME

---

media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild

add accidentally deleted `gnome-extra/zenity` to make saving and loading possible again

media-sound/bitwig: fixed dialog bug

---

media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild

```
ebuild.minorsyn               1
media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild: Useless blank line on line: 68
```
Noticed this in the travis output of #12 
Now repoman is happy :)

media-sound/bitwig repoman qa fix

---

tests/runtests.sh

Small change, drops xmlparse because it doesn't actually do anything. See https://github.com/gentoo/portage/blob/a514908c7fd29e668dd775d7a32c949dbc8fe7d7/repoman/pym/repoman/argparser.py#L118. The `xml_parse` variable isn't used anywhere in repoman's codebase
Adding `-d` doesn't do anything in our case but gets rid of the unnecessary `Note: use --include-dev (-d) to check dependencies for 'dev' profiles` output

Tests: repoman dont run xmlparse, include dev profiles

---

media-sound/drumkv1/drumkv1-0.8.2.ebuild
media-sound/drumkv1/drumkv1-9999.ebuild

Small change, adds the same fix as I already did in #30 and as it has been fixed in upstream `master` to the 0.8.2 version of drumkv

media-sound/drumkv1: Fix low res icon, update copyright header

---

tests/emerge_ebuild.sh

by using /tmp/distfiles as the portage distfiles dir. This directory is always writable by every user so doesn't fail.
Fixes #53

Tests: Fix gitr3 emerge test failure

---

.travis.yml
tests/emerge_random_ebuild.sh

This adds a simple script that uses the same foundation as the `emerge_new_or_changed_ebuilds.sh` script but does so for a random ebuild in the overlay.
Whilst ideally I'd like to do an emerge test for all the packages in the overlay every period that's simply going to take too long to finish. This is a means to still validate all our ebuilds continuously without the test taking ages.
Also because it's run from the `master` branch it serves as a way to feed the binary package cache for the `master` branch that's used by all pull requests. Which means we'll finally be able to make use of this cache for every PR :)

Test emerge random ebuild

---

tests/emerge_random_ebuild.sh

There was a tiny error in the find command which which meant the returned paths started with `./`, which mean the emerge test failed :x
This changes fixes that problem :)

Tests: fix random emerge test

---

.travis.yml

I just ran into this issue that whilst we now have a nice cache on master the PRs are actually not able to make use of it because the env vars set per job in the Travis CI matrix also impact if the cache is shared.
If the env vars differ the cache isn't shared :(
Fixed by getting rid of the marker env vars.
Unfortunately this means no clear overview in travis which job is which. Luckily we only have four and they have pretty distinguishable runtimes, so imho whilst it's less than ideal it's still doable.
See https://github.com/travis-ci/travis-ci/issues/5898 for a related issue about this. 
I didn't remove the newversioncheck env var because we don't need to share cache with that job, which means we can at least easily identify that one :)

Travis: Remove marker env vars

---

media-sound/synthv1/synthv1-9999.ebuild

Now the ebuild is the same as the one for samplv1

media-sound/synthv1 fix eautoreconf QA warning

---

media-sound/drumkv1/drumkv1-9999.ebuild

Now the ebuild is the same as the one for samplv1

media-sound/drumkv1 fix eautoreconf QA warning

---

tests/newversionchecker.toml

These were missing, which means we didn't get automatic version bump issues when they create a new release

Add missing applications to new version check

---

media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild
media-sound/bitwig-studio/bitwig-studio-2.1.1.ebuild
tests/packages/media-sound/bitwig-studio-1.3.16.conf
tests/packages/media-sound/bitwig-studio-2.1.1.conf

I tested it, bitwig needs API calls which only exist in jack2

media-sound/bitwig-studio: fix jack2 dependencies

---

media-sound/pure-data/pure-data-0.47_p1.ebuild

Small change to fix the following repoman reported QA issues
```
media-sound/pure-data/pure-data-0.47_p1.ebuild: RDEPEND: 'dev-lang/tcl' matches more than one slot, please specify an explicit slot and/or use the := or :* slot operator
media-sound/pure-data/pure-data-0.47_p1.ebuild: RDEPEND: 'dev-lang/tk[truetype]' matches more than one slot, please specify an explicit slot and/or use the := or :* slot operator
```
AFAIK Pd needs to be rebuilt if tcl or tk is updated.
Since Pd needs tcl >=8.5 and all tcl/tk versions in the gentoo tree match this requirement I've gone with `:=` so Pd will work with all slots and will rebuild on update.

media-sound/pure data fix missing slot operator QA issue

---

.travis.yml
tests/repoman.sh
tests/resources/repoman.sh

This PR enables Travis to post to PRs the results of the `repoman` run. See the comment directly below for an example :)
It uses https://github.com/koddsson/travis-github-pr-bot with some fixes/changes because it was specific to running `flake8` instead of any command line tool.
I'll try to get my changes upstreamed, but it's a small, single file project anyway, so not really a problem.

Tests: comment repoman output on PRs

---

tests/emerge_ebuild.sh
tests/emerge_new_or_changed_ebuilds.sh
tests/emerge_random_ebuild.sh
tests/repoman.sh
tests/resources/repoman.sh

Instead of syncing the entire tree every run.
This makes sure the tests are more stable, quicker and we don't hammer the gentoo mirror's all the time with our syncs

Tests: Use portage volume container

---

media-libs/libmonome/libmonome-9999.ebuild
media-libs/libmonome/metadata.xml

libmonome is needed to work with monome grid's https://monome.org/grid/
Apparently no one so far made an ebuild for it so here we go :)
Once merged I'll create a PR to update the monome Linux docs so people know they can install libmonome easily when using gentoo :)

add media-libs/libmonome

---

media-sound/serialosc/serialosc-9999.ebuild

This ensures submodules that are added later will be checked out.
Fixes the issue that the third-party/optparse submodule wasn't available

media-sound/serialosc: Fix only exclude libuv submodule

---

media-sound/serialosc/serialosc-1.4.1.ebuild
media-sound/serialosc/serialosc-9999.ebuild

Fixes #155 
Uses git instead of the release tarball because the tarball isn't complete (missing git submodules and the gitrev it was created from).

media-sounds/serialosc add version 1.4.1

---

.gitignore
.travis.yml
docs/generate-site.sh
docs/index.md.j2

This PR adds automatic publishing of an overview of all the packages in our overlay to the `gh-pages` branch, which is used by GitHub Pages to publish to https://gentoo-audio.github.io/audio-overlay
This gives us a free site we can use to link to for anyone interested in the overlay/which packages it contains.
The build uses https://github.com/simonvanderveldt/overlay-packagelist which is a pretty simple Python script that uses portage to return a list of all the packages and their properties which can then be used in a template. The page that's generated is based on a jinja2 template (`docs/index.md.j2`) so we can customize it as we please. I want to add the basic usage instructions to it in the future.
Based on some feedback from the kind folks at Travis I've also switched out …

Add script to publish package list to GitHub Pages

---

.travis.yml

Small change so the job config in Travis doesn't show the whole build config.
Difference for reference:
Current situation without matrix, the whole build config is shown when looking at a job's config
New situation using matrix, only the chosen job's config is shown

Travis: switch back to matrix builds

---

tests/resources/repoman.sh

Otherwise the build fails because the secrets/credentials are missing

Tests: disable posting repoman result to GitHub for 3rd party PRs

---

tests/emerge-ebuild.sh
tests/resources/emerge-ebuild.sh

`binpkg-multi-use` allows a binary package host to store binary packages for different USE flag combinations, meaning we'll get less cache misses because of differences in USE flags for common packages :)
This should help builds on Travis so they take less time/don't time out.
`binpkg-multi-use` was introduced as fix to this bug https://bugs.gentoo.org/150031

Tests: Use binpkg-multi-instance for better caching

---

tests/repoman.sh

Small fix to make sure we still receive the repoman results as comments on our own (non 3rd party) PRs

Tests: fix feedback to github for our own PRs

---

media-sound/cadence/cadence-9999-r4.ebuild

Because cadence relies on DBus and DBus support isn't currently available in JACK1
Also add missing dbus USE flags for PyQT5 and a2jmidi, both are required for Cadence to work
Fixes #195

media-sound/cadence replace virtual/jack dependency with media-sound/jack2

---

media-sound/cadence/cadence-9999-r5.ebuild

And make it depend on PyQt5's OpenGL support
Fixes #167

media-sound/cadence add opengl USE flag

---

media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild
media-sound/bitwig-studio/bitwig-studio-2.1.4.ebuild

Apparently the `SRC_URI` we were using no longer works.
Good thing, because now we're using `HTTPS` :)

media-sound/bitwig-studio update SRC_URI

---

media-sound/mididings/mididings-20120419.ebuild
media-sound/mididings/mididings-99999999.ebuild

Shouldn't need a revbump because --newuse should take care of triggering rebuilds.

media-sound/mididings: enable python 3.6

---

media-sound/cadence/cadence-9999-r6.ebuild

Also replace python version used in executable with scripts with
Fixes #187
Fixes #189 
This will probably time out on CI, it has to build some big Qt packages
[edit] And it did indeed time out. Validated locally, emerge is working fine, no QA issues.

media-sound/cadence fix Python dependencies

---

media-sound/cadence/cadence-9999-r6.ebuild

Noticed the homepage was set incorrectly to the main KXStudio page instead of the cadence page :)

media-sound/cadence use correct homepage URL

---

media-sound/sc3-plugins/sc3-plugins-3.9.1.ebuild
media-sound/sc3-plugins/sc3-plugins-9999.ebuild

The relevant changes have been merged upstream, see https://github.com/supercollider/sc3-plugins/pull/229

media-sound/sc3-plugins: remove redundant patch from live ebuild

---

.circleci/config.yml
.circleci/deploy-gh-pages.sh
.travis.yml
README.md
docs/generate-site.sh
tests/emerge-new-or-changed-ebuilds.sh
tests/emerge-random-ebuild.sh
tests/emerge-random-live-ebuild.sh
tests/repoman.sh
tests/resources/repoman.sh

This PR adds the required config to run our tests on CircleCI.
This should fix #244 in that the timeout on CircleCI is significantly longer (5 hours as far as I've been able to find) and it's easier to cache portage package cache between steps in a pipeline (called workflow in CircleCI terms) as well, which significantly speeds up the emerge tests.
I'd like to run this in parallel to Travis for a month or so to see how well it works.
Since only one service can/should update the GitHub Pages site I've removed publishing to GitHub Pages from the Travis config.
I've tested all jobs and all of them worked as expected, but I expect there will still be some small things that will cause problems. I'll fix those when they pop up.

Add CircleCI config

---

README.md

Small update to the readme to add `eselect repository` instructions

Readme: add eselect repository instructions

---

media-libs/libmonome/libmonome-9999.ebuild
media-sound/serialosc/serialosc-9999.ebuild
tests/repoman.sh
tests/resources/repoman.sh

These caused failures ever since `python-any-r1` was patched to fail in case `PYTHON_REQUIRED_USE` was used together with `python-any-r`, see https://github.com/gentoo/gentoo/pull/12492

Fix incorrect use of PYTHON_REQUIRED_USE when using python-any-r1

---

media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild
media-sound/bitwig-studio/bitwig-studio-2.5.1.ebuild

The xcb USE flag has been dropped and it's config option are now triggered using the X USE flag

bitwig-studio: Replace x11-libs/cairo[xcb] with x11-libs/cairo[X]

---

media-sound/carla/carla-9999.ebuild

It's no longer supported, see https://github.com/falkTX/Carla/issues/1031

media-sound/carla: Remove FFmpeg dependency

---

media-sound/ladish/files/ladish-1-gui-resources-only-when-enabled.patch
media-sound/ladish/files/ladish-9999-gui-resources-only-when-enabled.patch
media-sound/ladish/ladish-1-r1.ebuild
media-sound/ladish/ladish-9999.ebuild

flowcanvas has been removed from the gentoo tree and is no longer maintained. Since the gladish GUI is 90% flowcanvas there's no way to have the GUI without it, so remove the option to build the GUI/gladish
This also fixes the installation of the .desktop file and icons to be conditional on if the GUI is built or not, before they were always installed even if the GUI wasn't built.
This fixes the repoman failure we currently have for this package

media-sound/ladish: Drop option to build the GUI

---

tests/resources/emerge-ebuild.sh
tests/resources/repoman.sh

Otherwise we're waiting for ages to compile dev-lang/rust just because it's a dependency of librsvg nowadays

tests: Ensure we always use dev-lang/rust-bin

---

tests/resources/emerge-ebuild.sh

I noticed we were accidentally running some steps for every package when emerging multiple ebuilds instead of just once.
This PR cleans up the `emerge-ebuild.sh` script a bit, move common config out of the per package section, add some logging, fix some comments.
Bonus: It saves about 8% of time for the emerge of all non-live ebuilds vs before from my local testing (+-58 minutes instead of +-63) :)

tests: Only install tools and do configuration required for the tests once

---

tests/get-new-or-changed-ebuilds.sh

Ignore changes introduced in master after the current branch was branched for determining which ebuilds have changed
I noticed we were also getting tests run for ebuilds that had no changes in the branch of a PR. Turned out that was because there were changes made to them in master after the branch was branched. This PR fixes that by only looking at the changes in the branch and ignoring the changes done on master in the meantime.

tests: Fix determining which ebuilds have changed

---

media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild
media-sound/bitwig-studio/bitwig-studio-2.5.1.ebuild
media-sound/bitwig-studio/bitwig-studio-3.2.7.ebuild

`virtual/ffmpeg` has been dropped in https://github.com/gentoo/gentoo/commit/0e5b93b5315bdedab7c37f5bbe66b7fd60ba51ec update the ebuilds that depend on it to `media-video/ffmpeg`

Replace virtual/ffmpeg with media-video/ffmpeg

---

media-plugins/deteriorate-lv2/deteriorate-lv2-1.0.6.ebuild
media-plugins/deteriorate-lv2/deteriorate-lv2-9999.ebuild

Small fix for missing `PYTHON_DEPS` in `DEPEND`, triggered by deteriorate-lv2 failing to emerge on CI because no supported Python implementation was available.
There might be more packages that are missing this, I'll do a check this weekend.

media-plugins/deteriorate-lv2: Add missing PYTHON_DEPS to DEPEND

---

tests/emerge-new-or-changed-ebuilds.sh
tests/resources/packages/media-sound/guitarix.conf

The guitarix package has been remove since it's not available in the upstream gentoo repo but the test config was still there :)

tests: Remove unused guitarix config

---

media-plugins/fabla/fabla-1.3.2-r1.ebuild
media-plugins/fabla/fabla-1.9999.ebuild

It's been fixed in https://github.com/openAVproductions/openAV-Fabla/pull/61

media-plugins/fabla: Drop GCC9 patch from live ebuild

---

README.md
docs/index.md.j2

and remove layman install instructions, eselect repository has superseded it

Update repo description

---

media-sound/cadence/cadence-9999-r7.ebuild
media-sound/carla/carla-9999-r1.ebuild

The ebuild used PYTHON_MULTI_USEDEP inside python_gen_cond_dep. However,
according to python-single-r1.eclass(5), only PYTHON_SINGLE_USEDEP and
PYTHON_USEDEP can be set, where PYTHON_USEDEP is probably what was
intended by the original ebuild maintainer.
This commit updates the ebuild by using PYTHON_USEDEP instead of
PYTHON_MULTI_USEDEP.
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Adrian Schollmeyer <nex+b-g-o@nexadn.de>

media-sound/{carla,cadence}: Fix PYTHON_USEDEP

---

media-sound/bitwig-studio/bitwig-studio-4.0.4-r1.ebuild

fperms seems to escape the wildcard argument when it passes it to chmod making the chmod fail
Work around this by simply no longer using doins which requires fixing the permissions but just cp-ing everything in opt/bitwig-studio
This the same thing that's being done for other binary packages in the gentoo tree like openjdk-bin and slack
Fixes #480

media-sound/bitwig-studio: Fix install

---

media-plugins/sorcer/sorcer-1.1.3-r1.ebuild
media-plugins/sorcer/sorcer-9999.ebuild

media-plugins/sorcer-9999: Drop LV2 >=1.18.0 compatibility patch

---

profiles/package.unmask

The unmask was added to circumvent problems during the migration of media-libs/pyliblo from ::gentoo to ::audio-overlay. Since it is now obsolete, this commit drops the unmask.
Signed-off-by: Adrian Schollmeyer <nex+b-g-o@nexadn.de>

profiles: Drop pyliblo unmask

---

metadata/layout.conf

EAPI 6 is already very old and almost gone from ::gentoo. It is likely that it will be banned there sooner or later. It should at least be deprecated here and banned after migrating all ebuilds to newer EAPIs.
Signed-off-by: Adrian Schollmeyer <nex+b-g-o@nexadn.de>

metadata: Deprecate EAPI 6

---

media-libs/libmonome/libmonome-9999.ebuild
media-plugins/bitrot/bitrot-9999.ebuild
media-plugins/deteriorate-lv2/deteriorate-lv2-9999.ebuild
media-sound/serialosc/serialosc-9999.ebuild
x11-libs/ntk/ntk-9999.ebuild

waf-utils.eclass no longer supports EAPI=6. This PR bumps all consumers which still used EAPI=6 to use the most recent EAPI=8.
Closes: https://github.com/gentoo-audio/audio-overlay/issues/515

*/*: Bump consumers of waf-utils.eclass to EAPI 8

---

media-libs/libmonome/libmonome-9999.ebuild
media-sound/serialosc/serialosc-9999.ebuild
metadata/pkgcheck.conf
x11-libs/ntk/ntk-9999.ebuild

This PR contains a set of fixes as indicated by pkgcheck as well as a few `PYTHON_COMPAT` updates (dropping versions no longer supported in ::gentoo).
Overall these changes should not affect the build process itself.

Misc QA fixes

---

tests/resources/emerge-ebuild.sh

This requires setting a GitHub token in a public CI pipeline, allowing attackers to retrieve the token.

ci: don't post emerge QA messages as GitHub comments

---

media-sound/ladish/ladish-9999.ebuild

This one's required to make ladish compile again. The old upstream is dead. The rest is just fixing stuff while at it.

media-sound/ladish: fix upstream URL, update PYTHON_COMPAT, minor QA fixes

---

media-libs/pyliblo/pyliblo-0.10.0-r2.ebuild

These commits go alongside each other. Enabling tests is required for testing the python bumps.
Only using PEP517 is a minor quality improvement and independent of the rest of the changeset.
This PR is a requirement for building pyliblo on recent Gentoo systems without having to enable py3.9 support.

media-libs/pyliblo: Add tests, PEP517 and recent python versions

---

tests/resources/pkgcheck.sh

This old tool is no longer in use and causes problems in the CI pipeline.

tests: do not install unneeded pip dependency

---

media-sound/cadence/cadence-9999-r7.ebuild

Closes: https://github.com/gentoo-audio/audio-overlay/issues/516

media-sound/cadence: bump PYTHON_COMPAT to py3.10, QA fixes

---

media-libs/libmonome/libmonome-9999.ebuild
media-plugins/bitrot/bitrot-9999.ebuild

Closes: https://github.com/gentoo-audio/audio-overlay/issues/532

bitrot, monome: bump PYTHON_COMPAT to py3.10 and py3.11

---

media-sound/carla/carla-9999-r1.ebuild

Enables py3.11 and cleans up removed python targets.

media-sound/carla: enable py3.11

---

media-plugins/deteriorate-lv2/deteriorate-lv2-9999.ebuild
media-sound/ladish/ladish-1-r2.ebuild
media-sound/serialosc/serialosc-1.4.1.ebuild
media-sound/serialosc/serialosc-1.4.3.ebuild
media-sound/serialosc/serialosc-9999.ebuild

We have a bunch of software which is py3.9 or lower only. Since py3.9 is now deprecated in ::gentoo and py3.9 is removed from dependencies' PYTHON_COMPAT, we need to at least bump to py3.10 for these packages to work. This is done in this PR.
Closes: #535

*/*: Python bumps required to fix global scope failures

---

media-libs/pyliblo/pyliblo-0.10.0-r2.ebuild

pyliblo breaks with Cython 3, so we must block it.

media-libs/pyliblo: block cython-3

---

tests/resources/emerge-ebuild.sh

Gentoo now provides official binhosts. We should use them as they can reduce pipeline runtime (and thus the frequency of pipeline failures due to timeouts). As the official binhost packages are distributed over the Gentoo mirror infrastructure, these are highly available and thus also solve the issue of the pipeline depending on a single working binhost to function properly.
The binhost configuration is already supplied in the gentoo/stage3 Docker image, but the keys for the signatures must be fetched using getuto.

ci: use official Gentoo binhost
