- media-sound/cadence/cadence-9999-r1.ebuild
- media-sound/cadence/files/cadence-add-skip-stripping.patch
- media-sound/cadence/metadata.xml
> Add media-sound/cadence

- media-plugins/distrho-ports/distrho-ports-20170804.ebuild
- media-plugins/distrho-ports/distrho-ports-99999999.ebuild
No actual changes to the ebuild, just changed spaces to tabs
> media-plugins/distrho-ports: fix repoman QA warning for use of spaces instead of tabs

- licenses/FLTK
- x11-libs/ntk/files/ntk-dont-run-ldconfig.patch
- x11-libs/ntk/files/ntk-no-default-cflags-optimizations.patch
- x11-libs/ntk/metadata.xml
- x11-libs/ntk/ntk-9999.ebuild
Needed for #86 as well as the majority of the OpenAV plugins.
I still need to look at the CFLAGS that are being set by the wscript, so please don't merge yet :)
Wanted to get a heads-up from Travis if the rest is working.
> Add x11-libs/ntk

- media-sound/drumkv1/drumkv1-9999.ebuild
- media-sound/pure-data/pure-data-0.47_p1.ebuild
- media-sound/samplv1/samplv1-9999.ebuild
- media-sound/synthv1/synthv1-9999.ebuild
> Use xdg-utils eclass instead of fdo-mime

- media-plugins/distrho-ports/distrho-ports-20170804.ebuild
Seems like we forgot this when we added the package
> media-plugins/distrho-ports-20170804 keyword testing

- media-sound/bitwig-studio/bitwig-studio-1.3.16.ebuild
- media-sound/bitwig-studio/bitwig-studio-2.1.1.ebuild
Final package that's needed to fix #95
> media-sound/bitwig-studio use xdg-utils instead of fdo-mime

- media-video/praxis-live-bin/praxis-live-bin-3.1.0.ebuild
- tests/packages/media-video/praxis-live-bin-3.1.0.conf
This is the final package needed to fix #65
> media-video/praxis-live-bin fix tests

- media-sound/padthv1/padthv1-9999.ebuild
- media-sound/samplv1/samplv1-9999.ebuild
- media-sound/serialosc/serialosc-9999.ebuild
Some small fixes
-3 characters in total! :tada:
> Fix qa issues

- media-sound/cadence/cadence-9999-r2.ebuild
- media-sound/cadence/metadata.xml
Fix actually installing the Cadence Python sources
Conitionally depend on LADISH
Remove caterina test app
> media-sound/cadence Fix and cleanup install sources and deps

- media-sound/sc3-plugins/files/sc3-plugins-3.9.1-cmake-fix-nova-tt-nova-diskio-check.patch
- media-sound/sc3-plugins/metadata.xml
- media-sound/sc3-plugins/sc3-plugins-3.9.1.ebuild
- media-sound/sc3-plugins/sc3-plugins-9999.ebuild
Adds https://github.com/supercollider/sc3-plugins
> Add media-sound/sc3-plugins

- media-sound/ladish/ladish-1.ebuild
- media-sound/ladish/ladish-9999.ebuild
> media-sound/ladish remove -Werror

- media-sound/carla/carla-9999.ebuild
> media-sound/carla: Fix python-single to multi USEDEP

- .circleci/config.yml
- media-sound/mididings/files/mididings-20120419-boost_python.patch
- media-sound/mididings/files/mididings-99999999-boost_python.patch
- tests/get-new-or-changed-ebuilds.sh
- tests/repoman-new-or-changed-ebuilds.sh
- tests/repoman.sh
Fixes #312 
@nick87720z Could you check if this works for you as well?
> media-sound/mididings: Fix libboost_python<xy> detection

- media-sound/sc3-plugins/sc3-plugins-3.10.0.ebuild
- media-sound/sc3-plugins/sc3-plugins-9999.ebuild
- tests/emerge-ebuild.sh
- tests/emerge-new-or-changed-ebuilds.sh
- tests/emerge-random-ebuild.sh
- tests/emerge-random-live-ebuild.sh
- tests/newversioncheck.sh
- tests/resources/emerge-ebuild.sh
- tests/resources/repoman.sh
Fixes the following QA warnings
```
ebuild.badheader              2
media-sound/sc3-plugins/sc3-plugins-3.10.0.ebuild: line 1: Invalid Copyright
media-sound/sc3-plugins/sc3-plugins-9999.ebuild: line 1: Invalid Copyright
Non-Fatal QA errors found
```
> media-sound/sc3-plugins: update header

- .circleci/config.yml
- tests/emerge-all-ebuilds.sh
- tests/emerge-all-live-ebuilds.sh
- tests/emerge-ebuild.sh
- tests/resources/emerge-ebuild.sh
- tests/resources/packages/media-plugins/deteriorate-lv2.conf
- tests/resources/packages/media-plugins/distrho-ports.conf
- tests/resources/packages/media-plugins/fabla.conf
- tests/resources/packages/media-sound/bitwig-studio.conf
- tests/resources/packages/media-sound/cadence.conf
- tests/resources/packages/media-sound/drumkv1.conf
- tests/resources/packages/media-sound/guitarix.conf
- tests/resources/packages/media-sound/mididings.conf
- tests/resources/packages/media-sound/padthv1.conf
- tests/resources/packages/media-sound/samplv1.conf
- tests/resources/packages/media-sound/sequencer64.conf
- tests/resources/packages/media-sound/synthv1.conf
Tested on CircleCI, emerging all ebuilds took +- 2 hours, which seems acceptable so this PR also updates the CircleCI config to emerge all ebuilds daily instead of just a single ebuild.
> Tests: Add emerge all

- media-plugins/artyfx/artyfx-9999.ebuild
- media-plugins/fabla/fabla-1.9999.ebuild
- media-plugins/fabla/fabla-2.9999.ebuild
- media-plugins/fabla/files/fabla-1-gcc-9-remove-leading-underscore.patch
- media-plugins/fabla/files/fabla-2-gcc-9-remove-leading-underscore.patch
- media-plugins/sorcer/files/sorcer-gcc-9-remove-leading-underscore.patch
- media-plugins/sorcer/sorcer-9999.ebuild
- media-sound/luppp/luppp-9999.ebuild
- media-sound/sc3-plugins/sc3-plugins-3.10.0.ebuild
- media-sound/sc3-plugins/sc3-plugins-9999.ebuild
See https://github.com/gentoo/gentoo/commit/0ebbf5666970ba32c0a55bcabf7d2ccee1ea5e74
> Replace cmake-utils eclass with cmake eclass

- media-plugins/distrho-ports/distrho-ports-99999999.ebuild
Upstream has replaced make with meson
Fixes #360
> media-plugins/distrho-ports: Use meson to build the live ebuild

- media-plugins/deteriorate-lv2/deteriorate-lv2-1.0.6.ebuild
- media-plugins/deteriorate-lv2/deteriorate-lv2-9999.ebuild
> media-plugins/deteriorate-lv2: Update homepage

- media-plugins/x42-plugins/x42-plugins-20200714-r1.ebuild
Hopefully one of the final packages for #323
> media-plugins/x42-plugins: Use correct libdir

- media-plugins/bitrot/bitrot-9999.ebuild
> media-plugins/bitrot: Use correct libdir

- docs/index.md.j2
to be the same as in the readme
> docs: Update how to use section

- media-plugins/nekobi/files/nekobi-allow-configuring-which-plugin-types-to-build.patch
- tests/emerge-all-ebuilds.sh
- tests/emerge-all-live-ebuilds.sh
- tests/emerge-ebuild.sh
- tests/emerge-new-or-changed-ebuilds.sh
- tests/emerge-random-ebuild.sh
- tests/emerge-random-live-ebuild.sh
- tests/repoman.sh
- tests/resources/emerge-ebuild.sh
- tests/resources/repoman.sh
And fix/update tests
Fixes #469
> media-plugins/nekobi: Update patch to allow configuring what to build

- media-libs/pyliblo/metadata.xml
- media-sound/ladish/metadata.xml
- media-sound/new-session-manager/metadata.xml
- x11-libs/ntk/metadata.xml
This PR adds myself as co-maintainer for a few packages I'd like to maintain. Please merge if you'd like my help maintaining these.
> Add myself as co-maintainer for some packages
